"""image

Revision ID: 30c962585506
Revises: c87f5d90a355
Create Date: 2026-05-21 19:38:04.252838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "30c962585506"
down_revision: Union[str, None] = "c87f5d90a355"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts_post", "image")
    op.add_column(
        "refresh_tokens", sa.Column("is_revoked", sa.Boolean(), nullable=True)
    )
    op.alter_column(
        "refresh_tokens",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False
    )
    op.drop_constraint(
        op.f("refresh_tokens_user_id_fkey"), "refresh_tokens", type_="foreignkey"
    )
    op.create_foreign_key(None, "refresh_tokens", "auth_user", ["user_id"], ["id"])
    op.drop_column("refresh_tokens", "revoked")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens",
        sa.Column("revoked", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(
        op.f("refresh_tokens_user_id_fkey"),
        "refresh_tokens",
        "auth_user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.alter_column(
        "refresh_tokens",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("refresh_tokens", "is_revoked")
    op.add_column(
        "posts_post",
        sa.Column("image", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
