"""create2

Revision ID: 95d1c3c4e0e5
Revises: 01936e4ae7f6
Create Date: 2026-05-24 21:18:40.685381

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "95d1c3c4e0e5"
down_revision: Union[str, None] = "01936e4ae7f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
