"""initial_schema

Revision ID: ddfd7e327aef
Revises: 1f4686cbaef4
Create Date: 2026-05-24 21:46:31.329011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ddfd7e327aef"
down_revision: Union[str, None] = "1f4686cbaef4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
