"""1_initial_migration

Revision ID: fc31c346a323
Revises: 
Create Date: 2026-03-13 23:46:41.084325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc31c346a323'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_index(op.f('ix_auth_user_username'), 'auth_user', ['username'], unique=True)
    op.create_table('posts_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_group_id'), 'posts_group', ['id'], unique=False)
    op.create_index(op.f('ix_posts_group_slug'), 'posts_group', ['slug'], unique=True)
    op.create_table('posts_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('pub_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['posts_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_post_author_id'), 'posts_post', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_post_id'), 'posts_post', ['id'], unique=False)
    op.create_index(op.f('ix_posts_post_pub_date'), 'posts_post', ['pub_date'], unique=False)
    op.create_table('posts_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_comment_created'), 'posts_comment', ['created'], unique=False)
    op.create_index(op.f('ix_posts_comment_id'), 'posts_comment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_comment_id'), table_name='posts_comment')
    op.drop_index(op.f('ix_posts_comment_created'), table_name='posts_comment')
    op.drop_table('posts_comment')
    op.drop_index(op.f('ix_posts_post_pub_date'), table_name='posts_post')
    op.drop_index(op.f('ix_posts_post_id'), table_name='posts_post')
    op.drop_index(op.f('ix_posts_post_author_id'), table_name='posts_post')
    op.drop_table('posts_post')
    op.drop_index(op.f('ix_posts_group_slug'), table_name='posts_group')
    op.drop_index(op.f('ix_posts_group_id'), table_name='posts_group')
    op.drop_table('posts_group')
    op.drop_index(op.f('ix_auth_user_username'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
